version: "3.7"
services: 
  login-service:
    image: "${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG_NAME}"
    ports: 
    - 80:80
    networks:
      - cpdss-network
      - portainer_agent_network
    dns: 8.8.8.8
    healthcheck:
      test: "wget --no-verbose --spider http://localhost:80/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:   
          memory: 50M
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
        monitor: 15s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 15
        window: 120s
networks: 
  cpdss-network:
    external: true
  swarmpit_net:
    external: true
  portainer_agent_network:
    external: true