version: "3.7"
services: 
  envoy-writer-service:
    image: "${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG_NAME}"
    ports: 
    - ${PORTS}
    environment: 
    - DB_HOST=${DB_HOST}
    - DB_NAME=${DB_NAME} 
    - DB_USER=${DB_USER} 
    - DB_PASSWORD=${DB_PASSWORD} 
    - REST_PORT=8080
    - GRPC_PORT=8090
    - CPDSS_BUILD_ENV=${CPDSS_BUILD_ENV}
    - SHIP_URL=${SHIP_URL}
    - SHORE_URL=${SHORE_URL}
    - SALT=${SALT}
    dns: 8.8.8.8
    healthcheck:
      test: "wget --no-verbose --spider http://localhost:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
networks: 
  default:
    external: true
    name: cpdss-network